
# Site settings
testing-mode: false

url: "https://benjaminashbaugh.me"

baseurl: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Benjamin Ashbaugh"
title: "benjaminashbaugh.me"
#description: "scitronboy's blog and website: cool projects, tutorials, and articles about tech.  I blog and write tutorials about anything from python programming and web development to arduino and raspberry pi, for beginners and advanced users."

#keywords: "A, Benjamin, scitronboy, personal, blog, tutorials, 14, arduino, python, git, programming, making, DIY"
#favicon: "/img/favicon.ico"

################
# home navbar buttons #
################

homeButtons:
  - name: "About Me"
    href: "#about"
  - name: "Portfolio"
    href: "#portfolio"
  - name: "Blog"
    href: "blog"
  - name: "GitHub"
    href: "https://github.com/scitronboy"
    newtab: true
  - name: "Contact Me"
    href: "#contact"


################
# Blog Header layout #
################

black-favicon: "/img/white-lab-glass.png"

background-img: "../img/workbench.jpg"

##############################
# Color the browser elements #
##############################
color-browser: "#ffffff"
apple-status-bar-style: "white"

################
# Web app mode #
################

web-app-mode: False

# Icons for Web App mode

#icon-36p: "/img/web-app/icon-36p.png"
#icon-48p: "/img/web-app/icon-48p.png"
#icon-72p: "/img/web-app/icon-72p.png"
#icon-96p: "/img/web-app/icon-96p.png"
#icon-144p: "/img/web-app/icon-144p.png"
#icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

post-preview-words: 100

paginate: 10

email-share: True
fb-share: True
twitter-share: True
pinterest-share: True
linkedin-share: True
reddit-share: True
google-plus-share: False
tumblr-share: False
pocket-share: False
vkontakte-share: False

# disqus-shortname: "scitronboy-github-io"

syntax-highlight: True


###########
# Contact #
###########

contact_email: false
email:

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background

# if the author_blurb is not set, then this feature is skipped
#author_blurb: "Benjamin is a 14 year old boy who loves electronics, robotics, science, technology, programming, and making. Learn more <a href='/#about'>here</a>."
author_blurb_image: "/img/author.jpg"

##################
# Social Buttons #
##################

#social:
  ##- title: "facebook"
    ##url: "https://facebook.com/"
  ##- title: "twitter"
    ##url: "https://twitter.com/"
  #- title: "github"
    #url: "https://github.com/scitronboy"
  #- title: "stack overflow"
    #url: "https://stackexchange.com/users/11955944/scitronboy?tab=accounts"
  ##- title: "bitcoin"
    ##url: "https://blockchain.info/address/1LHuKC9Em3KA5yoZaf7nngnNdf9K7s2gSi"
  #- title: "rss"
    #url: "/feed.xml"


permalink: /:categories/:slug

collections:
    - update_collection

    
exclude: ["README.md", "scripts", "tips.txt", "no-serve", "optimize", ".github", "Gemfile"]

include: ["_redirects", "_headers"]

# Pagination path

paginate_path: "archive/page:num/"

# Enable minification SASS

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jemoji
  - jekyll-redirect-from
