
# Site settings
testing-mode: false

url: "https://scitronboy.github.io"

baseurl: ""

site_redirect_from: scitronboy.github.io
site_redirect_to: scitronboy.com

title: scitronboy.github.io
form-api-token: "4923b1bd96b8bc654e1dd3eb8f0869cd"


exclude: ["README.md", "scripts", "tips.txt", "no-serve", "optimize", ".github", "Gemfile", "index.html"]


sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jemoji
  - jekyll-redirect-from
