[[headers]]
for = "/*"
[headers.values]
# Server = "Netlify-scitronboy.com"
X-Content-Type-Options = "nosniff"
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"

[[headers]]
for = "/img/*"
[headers.values]
Cache-Control = "max-age=86400"

[[headers]]
for = "/css/*"
[headers.values]
Cache-Control = "max-age=172800"

[[headers]]
for = "/js/*"
[headers.values]
Cache-Control = "max-age=86400"



[[redirects]]
from = "https://benjaminashbaughme.netlify.com/*"
to = "https://benjaminashbaugh.me/:splat"
status = 301
force = true

[[redirects]]
from = "/other/:year/:slug"
to = "/other/:slug"
status = 301
force = true

[[redirects]]
from = "/projects/:year/:slug"
to = "/projects/:slug"
status = 301
force = true

[[redirects]]
from = "/code/:year/:slug"
to = "/code/:slug"
status = 301
force = true