[[headers]]
for = "/*"
[headers.values]
Server = "Netlify-scitronboy.com"
X-Content-Type-Options = "nosniff"
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"

# Cache-Control = "max-age=86400"

[[redirects]]
from = "https://scitronboycom.netlify.com/*"
to = "https://scitronboy.com/:splat"
status = 301
force = true
