site_url: 'https://benjaminashbaugh.me/'

backend:
  name: github
  repo: scitronboy/benjaminashbaugh
  branch: published

media_folder: 'img/uploads'

publish_mode: editorial_workflow
show_preview_links: true

logo_url: 'https://benjaminashbaugh.me/img/favicon/favicon-96x96.png'

slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    preview_path: '{{category}}/{{url_slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'SectionType', name: 'section-type', widget: 'hidden', default: 'post' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', format: 'YYYY-MM-DD'}
      - { label: 'Update Text', name: 'update-text', widget: 'string', required: false }
      - { label: 'Last Modification (SEO)', name: 'lastmod', widget: 'datetime', format: 'YYYY-MM-DD'}
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Thumbnail', name: 'image', widget: 'image', required: false }
      - { label: 'Header Image', name: 'top-image', widget: 'image', required: false }
      - { label: 'URL slug', name: 'slug', widget: 'string' }
      - { label: 'URL slug (again)', name: 'url_slug', widget: 'string' }
      - { label: 'Category', name: 'category', widget: 'select', options: ['3dp', 'code', 'projects', 'other']}
      - { label: 'Tags', name: 'tags', widget: 'select', multiple: true, options: ['3d-printing', 'arduino', 'code', 'game', 'jekyll', 'project', 'python', 'review', 'tutorial', 'web-dev']}
      - { label: 'Post Description', name: 'postdescription', widget: 'string' }
      - { label: 'SEO Title', name: 'titletag', widget: 'string' }
      - { label: 'SEO Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'updates'
      label: 'Updates'
      folder: '_update_collection/'
      create: true
      slug: '{{slug}}'
      preview_path: ''
      editor:
        preview: false
      fields:
        - { label: 'Title', name: 'title', widget: 'string' }
        - { label: 'Date', name: 'date', widget: 'datetime', format: 'YYYY-MM-DD'}
        - { label: 'Visible', name: 'visible', widget: 'boolean', required: false }
        - { label: 'Title Link', name: 'link', widget: 'string', required: false }
        - { label: 'Message', name: 'body', widget: 'markdown' }
  - name: 'projects'
      label: 'Projects'
      folder: '_home_portfolio_collection/'
      create: true
      slug: '{{slug}}'
      preview_path: '#portfolio'
      editor:
        preview: false
      fields:
        - { label: 'Title', name: 'title', widget: 'string' }
        - { label: 'Date', name: 'date', widget: 'datetime', format: 'YYYY-MM-DD' }
        - { label: 'Section (0=featured, 1=other)', name: 'section', widget: 'number', value_type: 'int' }
        - { label: 'Image', name: 'image', widget: 'image', required: false }
        - { label: 'Visible', name: 'visible', widget: 'boolean', required: false }
        - { label: 'Title Link', name: 'link', widget: 'string', required: false }
        - { label: 'Message', name: 'body', widget: 'markdown' }
